# Generated by Django 4.1 on 2022-10-17 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appuser'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'post')},
        ),
    ]
