# Generated by Django 4.1 on 2022-10-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_vote_post_alter_vote_voter'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
